### ISSUE TITLE
Discord embed is broken

### ISSUE THREAD

**Issue by tuzonghua** [ThornbushHQ/FixBluesky#11]
Recently, when using the `bsyy.app` URL, the Discord embed doesn't seem to work anymore. Clicking on the link also gives the following error message:
```
Failed to login to Bluesky! 

 Error: Authentication Required 

 Error: Failed to login to Bluesky!
    at index.js:37:4636
    at async index.js:17:34270
```

**Comment by TheAppleFreak** [comment]
+1 for this issue

**Comment by midblep** [comment]
yep its broken still

**Comment by GeorgeWL** [comment]
still broken

**Comment by Lexedia** [comment]
Hi, it seems the author hasn't committed to the repo for quite a while now, I took the liberty to [fork the repo](https://github.com/Rapougnac/VixBluesky), and push some fixes, you can use this service in the meantime.
